-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1200@60.03", position = "960x0", scale = 1.33 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "-576x-64", scale = 1.25 })
